version: "3"
services:
    php_dev:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        depends_on: 
            - db
        volumes: 
            - .:/var/www/html
        ports:
            - 8888:80
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on: 
            - db
        container_name: phpmyadmin
        environment: 
            - PMA_ARBITRARY=1
            
        restart: always
        ports: 
            - 8889:80
        volumes: 
            - /sessions
    db:
        image: mysql:5.7
        ports:
            - 13306:3306
        volumes: 
             - ./db:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: docker_php
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: docker_php
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_HOST: '%'
volumes:
    db:
        driver: local
